### ISSUE TITLE
Control-key shortcuts (like Control-Z) don't appear to work on a Chromebook

### ISSUE THREAD

**Issue by justvanrossum** [BlackFoundryCom/fontra#122]
See https://twitter.com/cosimolupo/status/1570726540442488833

**Comment by anthrotype** [comment]
thanks! On your mac, do you use CTRL or COMMAND as fontra's modifier key? I wonder if that key itself could be user-configured maybe.

**Comment by justvanrossum** [comment]
I look at `event.metaKey` on macOS, and at `event.controlKey` on all other platforms. But it hasn't been properly tested, and I may do things wrong:

https://github.com/BlackFoundryCom/fontra/blob/11c9bc4842baca1fd17d359573a10f1cce1afa07/src/fontra/client/core/utils.js#L152-L158

- https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey
- https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/ctrlKey

**Comment by anthrotype** [comment]
I think it's called `ctrlKey`, not `controlKey`, could that be it?

**Comment by justvanrossum** [comment]
I think I see the bug right there... It should be `event.ctrlKey`, not `event.controlKey`!

PR coming up :)

**Comment by justvanrossum** [comment]
You win!

**Comment by anthrotype** [comment]
ahhahah! I just tested it locally and it works now 👯‍♀️
