### ISSUE TITLE
UFO changes not showing up in other editors

### ISSUE THREAD

**Issue by cjdunn** [BlackFoundryCom/fontra#129]
If i make outline changes to a glyph in Fontra I understand that changes should be autosaved. And I can see the changes if I open Fontra in a new browser. But If I open up that UFO in another UFO editor (eg Robofont) I don't see the new outline changes. I also don't see any changes made to the UFO in my git repo. 

How can I see the updated UFO in another editor? Should autosave vs manual save be a more explicit option? Eg autosave by default (which could be turned off if wanted), and also have an option to explicitly "save now". 

It's unsettling to think about doing a bunch of working and hoping things have been autosaved, only to realize something went wrong. I would like the option to "save now" before closing the browser for peace of mind. 

Thanks for you consideration!

**Comment by justvanrossum** [comment]
Are you looking at a single UFO or a designspace file? If the former, you may want to refresh you Fontra install, as that feature got added after your first demo.

**Comment by justvanrossum** [comment]
Btw. do not use Fontra for real work yet, unless you know exactly what you're doing.

**Comment by cjdunn** [comment]
Oooh, nice I can see the changes in git now. And thanks for the tip about not using this for real work yet. So far I'm still just experimenting

**Comment by justvanrossum** [comment]
Fontra is currently for the adventurous, and therefore not without risk... Thanks for your feedback, and keep it coming!
