### ISSUE TITLE
CLI: argparse subparsers added multiple times

### ISSUE THREAD

**Issue by madig** [BlackFoundryCom/fontra#141]
https://github.com/BlackFoundryCom/fontra/blob/986458b0e4c5f7e1d02d3beb00b4521364f66e56/src/fontra/__main__.py#L20-L21

Multiple entry points cause the `filesystem` subparser to be added, which stops working in Python 3.11 due to https://github.com/python/cpython/issues/83897.

I'm not sure what the intended effect of adding them multiple times is?

**Comment by justvanrossum** [comment]
Hmm, my first question is: why are there multiple entry-points named `filesystem`? I am not sure what's wrong here. I do see that it gets added multiple times, but this isn't intentional.

**Comment by justvanrossum** [comment]
I have no idea why this happens:
```python
>>> from importlib.metadata import entry_points
>>> for ep in entry_points(group="fontra.projectmanagers"):
...   print(ep)
... 
EntryPoint(name='filesystem', value='fontra.filesystem.projectmanager:FileSystemProjectManagerFactory', group='fontra.projectmanagers')
EntryPoint(name='filesystem', value='fontra.filesystem.projectmanager:FileSystemProjectManagerFactory', group='fontra.projectmanagers')
EntryPoint(name='rcjk', value='fontra_rcjk.projectmanager:RCJKProjectManagerFactory', group='fontra.projectmanagers')
>>> 
```

**Comment by justvanrossum** [comment]
Ah, it only happens when we install as editable:

Double entry point:
`pip install -e .`

Single entry point:
`pip install .`

**Comment by justvanrossum** [comment]
Maybe the shim `setup.py` is causing it?

**Comment by madig** [comment]
Deleting it does not help.

**Comment by justvanrossum** [comment]
Leaning towards "bug in pip". Or setuptools. Would you like to experiment with a different build back end?

**Comment by justvanrossum** [comment]
Using [hatch](https://hatch.pypa.io/latest/) instead of setuptools doesn't resolve the issue.

**Comment by madig** [comment]
I can help switch to hatch, which is nice for other reasons. I guess this is a chance to contribute to Python packaging :)
